//---
var DATA = {
    //---
    items:[
        //---
        { id:'item_factorioDrillT1', label:'item_factorioDrillT1', img:'img/factorio/DrillT1.png', cases:4, speed:0.25, pollution:12, energy:{ id:'item_factorioCoal', count:0.0375 }, manual:true, recipe:{ time:2, output:1, inputs:[{ id:'item_factorioIronWheel', count:3 },{ id:'item_factorioIronPlate', count:3 },{ id:'item_factorioFurnaceT1', count:1 }] } },
        { id:'item_factorioDrillT2', label:'item_factorioDrillT2', img:'img/factorio/DrillT2.png', cases:9, speed:0.5, moduleSlots:3, pollution:10, energy:{ id:'item_factorioElectricity', count:90 }, manual:true, recipe:{ time:2, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:3 },{ id:'item_factorioIronWheel', count:5 },{ id:'item_factorioIronPlate', count:10 }] } },
        //---
        { id:'item_factorioCoal', label:'item_factorioCoal', img:'img/factorio/Coal.png', storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioDrillT1','item_factorioDrillT2' ], manual:true, recipe:{ time:1, output:1 } },
        { id:'item_factorioStone', label:'item_factorioStone', img:'img/factorio/Stone.png', storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioDrillT1','item_factorioDrillT2' ], manual:true, recipe:{ time:1, output:1 } },
        { id:'item_factorioIron', label:'item_factorioIron', img:'img/factorio/Iron.png', storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioDrillT1','item_factorioDrillT2' ], manual:true, recipe:{ time:1, output:1 } },
        { id:'item_factorioCopper', label:'item_factorioCopper', img:'img/factorio/Copper.png', storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioDrillT1','item_factorioDrillT2' ], manual:true, recipe:{ time:1, output:1 } },
        { id:'item_factorioUranium', label:'item_factorioUranium', img:'img/factorio/Uranium.png', reqs:[{ id:'item_factorioUraniumProcessing', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioDrillT2' ], recipe:{ time:2, output:1, inputs:[{ id:'item_factorioSulfuricAcid', count:1 }] } },
        //---
        { id:'item_factorioFurnaceT1', label:'item_factorioFurnaceT1', img:'img/factorio/FurnaceT1.png', cases:4, speed:1, pollution:2, energy:{ id:'item_factorioCoal', count:0.0225 }, manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioStone', count:5 }] } },
        { id:'item_factorioFurnaceT2', label:'item_factorioFurnaceT2', img:'img/factorio/FurnaceT2.png', reqs:[{ id:'item_factorioMaterial1', count:1 }], cases:4, speed:2, pollution:4, energy:{ id:'item_factorioCoal', count:0.0225 }, manual:true, recipe:{ time:3, output:1, inputs:[{ id:'item_factorioSteelPlate', count:6 },{ id:'item_factorioStoneBrick', count:10 }] } },
        { id:'item_factorioFurnaceT3', label:'item_factorioFurnaceT3', img:'img/factorio/FurnaceT3.png', reqs:[{ id:'item_factorioMaterial2', count:1 }], cases:9, speed:2, moduleSlots:2, pollution:1, energy:{ id:'item_factorioElectricity', count:180 }, manual:true, recipe:{ time:5, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioSteelPlate', count:10 },{ id:'item_factorioStoneBrick', count:10 }] } },
        //---
        { id:'item_factorioStoneBrick', label:'item_factorioStoneBrick', img:'img/factorio/StoneBrick.png', storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioFurnaceT1','item_factorioFurnaceT2','item_factorioFurnaceT3' ], recipe:{ time:3.2, output:1, inputs:[{ id:'item_factorioStone', count:2 }] } },
        { id:'item_factorioIronPlate', label:'item_factorioIronPlate', img:'img/factorio/IronPlate.png', storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioFurnaceT1','item_factorioFurnaceT2','item_factorioFurnaceT3' ], recipe:{ time:3.2, output:1, inputs:[{ id:'item_factorioIron', count:1 }] } },
        { id:'item_factorioCopperPlate', label:'item_factorioCopperPlate', img:'img/factorio/CopperPlate.png', storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioFurnaceT1','item_factorioFurnaceT2','item_factorioFurnaceT3' ], recipe:{ time:3.2, output:1, inputs:[{ id:'item_factorioCopper', count:1 }] } },
        { id:'item_factorioSteelPlate', label:'item_factorioSteelPlate', img:'img/factorio/SteelPlate.png', reqs:[{ id:'item_factorioSteelTech', count:1 }], storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioFurnaceT1','item_factorioFurnaceT2','item_factorioFurnaceT3' ], recipe:{ time:16, output:1, inputs:[{ id:'item_factorioIronPlate', count:5 }] } },
        //---
        { id:'item_factorioPump', label:'item_factorioPump', img:'img/factorio/Pump.png', cases:4, speed:1, manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:2 },{ id:'item_factorioIronWheel', count:1 },{ id:'item_factorioPipe', count:1 }] } },
        //---
        { id:'item_factorioWater', label:'item_factorioWater', img:'img/factorio/Water.png', storage:{ base:25000, id:'item_factorioStorageTank', count:25000 }, machines:[ 'item_factorioPump' ], recipe:{ time:1, output:1200 } },
        //---
        { id:'item_factorioCentrifuge', label:'item_factorioCentrifuge', img:'img/factorio/Centrifuge.png', reqs:[{ id:'item_factorioUraniumProcessing', count:1 }], cases:9, speed:1, pollution:4, energy:{ id:'item_factorioElectricity', count:350 }, manual:true, recipe:{ time:4, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:100 },{ id:'item_factorioConcrete', count:100 },{ id:'item_factorioIronWheel', count:100 },{ id:'item_factorioSteelPlate', count:50 }] } },
        //---
        { id:'item_factorioNuclearFuel', label:'item_factorioNuclearFuel', img:'img/factorio/NuclearFuel.png', reqs:[{ id:'item_factorioUraniumProcessing', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioCentrifuge' ], recipe:{ time:200, output:10, inputs:[{ id:'item_factorioUranium', count:200 },{ id:'item_factorioIronPlate', count:200 }] } },
        //---
        { id:'item_factorioBoiler', label:'item_factorioBoiler', img:'img/factorio/Boiler.png', cases:6, speed:1, pollution:30, energy:{ id:'item_factorioCoal', count:0.45 }, manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioPipe', count:4 },{ id:'item_factorioFurnaceT1', count:1 }] } },
        { id:'item_factorioNuclearReactor', label:'item_factorioNuclearReactor', img:'img/factorio/NuclearReactor.png', reqs:[{ id:'item_factorioNuclearPower', count:1 }], cases:25, speed:2, energy:{ id:'item_factorioNuclearFuel', count:0.01 }, manual:true, recipe:{ time:8, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:500 },{ id:'item_factorioConcrete', count:500 },{ id:'item_factorioCopperPlate', count:500 },{ id:'item_factorioSteelPlate', count:500 }] } },
        //---
        { id:'item_factorioSteam', label:'item_factorioSteam', img:'img/factorio/Steam.png', storage:{ base:25000, id:'item_factorioStorageTank', count:25000 }, machines:[ 'item_factorioBoiler','item_factorioNuclearReactor' ], recipe:{ time:1, output:60, inputs:[{ id:'item_factorioWater', count:60 }] } },
        //---
        { id:'item_factorioSteamEngine', label:'item_factorioSteamEngine', img:'img/factorio/SteamEngine.png', cases:15, speed:1, energy:{ id:'item_factorioSteam', count:30 }, manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioIronWheel', count:8 },{ id:'item_factorioIronPlate', count:10 },{ id:'item_factorioPipe', count:5 }] } },
        { id:'item_factorioSolarPanel', label:'item_factorioSolarPanel', img:'img/factorio/SolarPanel.png', reqs:[{ id:'item_factorioSolarEnergy', count:1 }], cases:9, speed:0.05, manual:true, recipe:{ time:10, output:1, inputs:[{ id:'item_factorioCopperPlate', count:5 },{ id:'item_factorioElectronicCircuit', count:15 },{ id:'item_factorioSteelPlate', count:5 }] } },
        { id:'item_factorioSteamTurbine', label:'item_factorioSteamTurbine', img:'img/factorio/SteamTurbine.png', reqs:[{ id:'item_factorioNuclearPower', count:1 }], cases:15, speed:6.5, energy:{ id:'item_factorioSteam', count:60 }, manual:true, recipe:{ time:3, output:1, inputs:[{ id:'item_factorioCopperPlate', count:50 },{ id:'item_factorioIronWheel', count:50 },{ id:'item_factorioPipe', count:20 }] } },
        //---
        { id:'item_factorioElectricity', label:'item_factorioElectricity', img:'img/factorio/Electricity.png', storage:{ base:25000, id:'item_factorioAccumulator', count:25000 }, machines:[ 'item_factorioSteamEngine','item_factorioSolarPanel','item_factorioSteamTurbine' ], recipe:{ time:1, output:900 } },
        //---
        { id:'item_factorioPumpjack', label:'item_factorioPumpjack', img:'img/factorio/Pumpjack.png', reqs:[{ id:'item_factorioOilProcessing', count:1 }], cases:9, speed:1, moduleSlots:2, pollution:10, energy:{ id:'item_factorioElectricity', count:90 }, manual:true, recipe:{ time:5, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:5 },{ id:'item_factorioIronWheel', count:10 },{ id:'item_factorioPipe', count:10 },{ id:'item_factorioSteelPlate', count:5 }] } },
        //---
        { id:'item_factorioCrudeOil', label:'item_factorioCrudeOil', img:'img/factorio/CrudeOil.png', reqs:[{ id:'item_factorioOilProcessing', count:1 }], storage:{ base:50, id:'item_factorioBarrel', count:50 }, machines:[ 'item_factorioPumpjack' ], recipe:{ time:1, output:2 } },
        //---
        { id:'item_factorioRefinery', label:'item_factorioRefinery', img:'img/factorio/Refinery.png', reqs:[{ id:'item_factorioOilProcessing', count:1 }], cases:25, speed:1, moduleSlots:3, pollution:6, energy:{ id:'item_factorioElectricity', count:420 }, manual:true, recipe:{ time:8, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:10 },{ id:'item_factorioIronWheel', count:10 },{ id:'item_factorioPipe', count:10 },{ id:'item_factorioSteelPlate', count:15 },{ id:'item_factorioStoneBrick', count:10 }] } },
        //---
        { id:'item_factorioPetroleumGas', label:'item_factorioPetroleumGas', img:'img/factorio/PetroleumGas.png', reqs:[{ id:'item_factorioOilProcessing', count:1 }], storage:{ base:50, id:'item_factorioBarrel', count:50 }, machines:[ 'item_factorioRefinery' ], recipe:{ time:5, output:45, inputs:[{ id:'item_factorioCrudeOil', count:100 }] } },
        { id:'item_factorioHeavyOil', label:'item_factorioHeavyOil', img:'img/factorio/HeavyOil.png', reqs:[{ id:'item_factorioOilProcessing', count:1 }], storage:{ base:50, id:'item_factorioBarrel', count:50 }, machines:[ 'item_factorioRefinery' ], recipe:{ time:5, output:25, inputs:[{ id:'item_factorioCrudeOil', count:100 },{ id:'item_factorioWater', count:50 }] } },
        //---
        { id:'item_factorioChemicalPlant', label:'item_factorioChemicalPlant', img:'img/factorio/ChemicalPlant.png', reqs:[{ id:'item_factorioOilProcessing', count:1 }], cases:9, speed:1, pollution:4, energy:{ id:'item_factorioElectricity', count:210 }, manual:true, recipe:{ time:5, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:5 },{ id:'item_factorioIronWheel', count:5 },{ id:'item_factorioPipe', count:5 },{ id:'item_factorioSteelPlate', count:5 }] } },
        //---
        { id:'item_factorioPlasticBar', label:'item_factorioPlasticBar', img:'img/factorio/PlasticBar.png', reqs:[{ id:'item_factorioPlastics', count:1 }], storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioChemicalPlant' ], recipe:{ time:1, output:2, inputs:[{ id:'item_factorioCoal', count:1 },{ id:'item_factorioPetroleumGas', count:20 }] } },
        { id:'item_factorioLightOil', label:'item_factorioLightOil', img:'img/factorio/LightOil.png', reqs:[{ id:'item_factorioOilProcessing', count:1 }], storage:{ base:50, id:'item_factorioBarrel', count:50 }, machines:[ 'item_factorioChemicalPlant' ], recipe:{ time:2, output:30, inputs:[{ id:'item_factorioHeavyOil', count:40 },{ id:'item_factorioWater', count:30 }] } },
        { id:'item_factorioLubricant', label:'item_factorioLubricant', img:'img/factorio/Lubricant.png', reqs:[{ id:'item_factorioLubricantTech', count:1 }], storage:{ base:50, id:'item_factorioBarrel', count:50 }, machines:[ 'item_factorioChemicalPlant' ], recipe:{ time:1, output:10, inputs:[{ id:'item_factorioHeavyOil', count:10 }] } },
        { id:'item_factorioSulfur', label:'item_factorioSulfur', img:'img/factorio/Sulfur.png', reqs:[{ id:'item_factorioSulfurTech', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioChemicalPlant' ], recipe:{ time:1, output:2, inputs:[{ id:'item_factorioPetroleumGas', count:30 },{ id:'item_factorioWater', count:30 }] } },
        { id:'item_factorioSulfuricAcid', label:'item_factorioSulfuricAcid', img:'img/factorio/SulfuricAcid.png', reqs:[{ id:'item_factorioSulfurTech', count:1 }], storage:{ base:50, id:'item_factorioBarrel', count:50 }, machines:[ 'item_factorioChemicalPlant' ], recipe:{ time:1, output:50, inputs:[{ id:'item_factorioIronPlate', count:1 },{ id:'item_factorioSulfur', count:5 },{ id:'item_factorioWater', count:100 }] } },
        { id:'item_factorioBattery', label:'item_factorioBattery', img:'img/factorio/Battery.png', reqs:[{ id:'item_factorioBatteryTech', count:1 }], storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioChemicalPlant' ], recipe:{ time:4, output:1, inputs:[{ id:'item_factorioCopperPlate', count:1 },{ id:'item_factorioIronPlate', count:1 },{ id:'item_factorioSulfuricAcid', count:20 }] } },
        { id:'item_factorioSolidFuel', label:'item_factorioSolidFuel', img:'img/factorio/SolidFuel.png', reqs:[{ id:'item_factorioOilProcessing2', count:1 }], storage:{ base:50, id:'item_factorioBarrel', count:50 }, machines:[ 'item_factorioChemicalPlant' ], recipe:{ time:2, output:1, inputs:[{ id:'item_factorioLightOil', count:10 }] } },
        //---
        { id:'item_factorioAssemblerT1', label:'item_factorioAssemblerT1', img:'img/factorio/AssemblerT1.png', reqs:[{ id:'item_factorioAutomation1', count:1 }], cases:9, speed:0.5, energy:{ id:'item_factorioElectricity', count:75 }, manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:3 },{ id:'item_factorioIronWheel', count:5 },{ id:'item_factorioIronPlate', count:9 }] } },
        { id:'item_factorioAssemblerT2', label:'item_factorioAssemblerT2', img:'img/factorio/AssemblerT2.png', reqs:[{ id:'item_factorioAutomation2', count:1 }], cases:9, speed:0.75, moduleSlots:2, energy:{ id:'item_factorioElectricity', count:150 }, manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioAssemblerT1', count:1 },{ id:'item_factorioElectronicCircuit', count:3 },{ id:'item_factorioIronWheel', count:5 },{ id:'item_factorioSteelPlate', count:2 }] } },
        { id:'item_factorioAssemblerT3', label:'item_factorioAssemblerT3', img:'img/factorio/AssemblerT3.png', reqs:[{ id:'item_factorioAutomation3', count:1 }], cases:9, speed:1.25, moduleSlots:4, energy:{ id:'item_factorioElectricity', count:375 }, manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioAssemblerT2', count:2 },{ id:'item_factorioSpeedModule1', count:4 }] } },
        //---
        { id:'item_factorioPipe', label:'item_factorioPipe', img:'img/factorio/Pipe.png', storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioIronPlate', count:1 }] } },
        { id:'item_factorioIronWheel', label:'item_factorioIronWheel', img:'img/factorio/IronWheel.png', storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioIronPlate', count:2 }] } },
        { id:'item_factorioRadar', label:'item_factorioRadar', img:'img/factorio/Radar.png', storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:5 },{ id:'item_factorioIronWheel', count:5 },{ id:'item_factorioIronPlate', count:10 }] } },
        { id:'item_factorioCable', label:'item_factorioCable', img:'img/factorio/Cable.png', storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:0.5, output:2, inputs:[{ id:'item_factorioCopperPlate', count:1 }] } },
        { id:'item_factorioElectronicCircuit', label:'item_factorioElectronicCircuit', img:'img/factorio/ElectronicCircuit.png', storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioCable', count:1 },{ id:'item_factorioIronPlate', count:1 }] } },
        { id:'item_factorioAdvancedCircuit', label:'item_factorioAdvancedCircuit', img:'img/factorio/AdvancedCircuit.png', reqs:[{ id:'item_factorioElectronics1', count:1 }], storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:6, output:1, inputs:[{ id:'item_factorioCable', count:4 },{ id:'item_factorioElectronicCircuit', count:2 },{ id:'item_factorioPlasticBar', count:2 }] } },
        { id:'item_factorioEngineUnit', label:'item_factorioEngineUnit', img:'img/factorio/EngineUnit.png', reqs:[{ id:'item_factorioEngineTech', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], recipe:{ time:10, output:1, inputs:[{ id:'item_factorioIronWheel', count:1 },{ id:'item_factorioPipe', count:2 },{ id:'item_factorioSteelPlate', count:1 }] } },
        { id:'item_factorioFlyingRobot', label:'item_factorioFlyingRobot', img:'img/factorio/FlyingRobot.png', reqs:[{ id:'item_factorioRobotics', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:20, output:1, inputs:[{ id:'item_factorioBattery', count:2 },{ id:'item_factorioElectricEngineUnit', count:1 },{ id:'item_factorioElectronicCircuit', count:3 },{ id:'item_factorioSteelPlate', count:1 }] } },
        { id:'item_factorioRocketControlUnit', label:'item_factorioRocketControlUnit', img:'img/factorio/RocketControlUnit.png', reqs:[{ id:'item_factorioRocketControlUnitTech', count:1 }], storage:{ base:10, id:'item_factorioChest', count:10 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:30, output:1, inputs:[{ id:'item_factorioProcessingUnit', count:1 },{ id:'item_factorioSpeedModule1', count:1 }] } },
        { id:'item_factorioLowDensityStructure', label:'item_factorioLowDensityStructure', img:'img/factorio/LowDensityStructure.png', reqs:[{ id:'item_factorioLowDensityStructureTech', count:1 }], storage:{ base:10, id:'item_factorioChest', count:10 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:20, output:1, inputs:[{ id:'item_factorioCopperPlate', count:20 },{ id:'item_factorioPlasticBar', count:5 },{ id:'item_factorioSteelPlate', count:2 }] } },
        { id:'item_factorioPowerArmor', label:'item_factorioPowerArmor', img:'img/factorio/PowerArmor.png', storage:{ base:1 }, reqs:[{ id:'item_factorioPowerArmorTech', count:1 }], machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:25, output:1, inputs:[{ id:'item_factorioEfficiencyModule2', count:25 },{ id:'item_factorioElectricEngineUnit', count:40 },{ id:'item_factorioLowDensityStructure', count:30 },{ id:'item_factorioProcessingUnit', count:60 },{ id:'item_factorioSpeedModule2', count:25 }] } },
        { id:'item_factorioSatellite', label:'item_factorioSatellite', img:'img/factorio/Satellite.png', reqs:[{ id:'item_factorioSpaceScience', count:1 }], storage:{ base:1 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:5, output:1, inputs:[{ id:'item_factorioAccumulator', count:100 },{ id:'item_factorioLowDensityStructure', count:100 },{ id:'item_factorioProcessingUnit', count:100 },{ id:'item_factorioRadar', count:5 },{ id:'item_factorioRocketFuel', count:50 },{ id:'item_factorioSolarPanel', count:100 }] } },
        { id:'item_factorioConcrete', label:'item_factorioConcrete', img:'img/factorio/Concrete.png', reqs:[{ id:'item_factorioConcreteTech', count:1 }], storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioAssemblerT2','item_factorioAssemblerT3' ], recipe:{ time:10, output:10, inputs:[{ id:'item_factorioIron', count:1 },{ id:'item_factorioStoneBrick', count:5 },{ id:'item_factorioWater', count:100 }] } },
        { id:'item_factorioProcessingUnit', label:'item_factorioProcessingUnit', img:'img/factorio/ProcessingUnit.png', reqs:[{ id:'item_factorioElectronics3', count:1 }], storage:{ base:100, id:'item_factorioChest', count:100 }, machines:[ 'item_factorioAssemblerT2','item_factorioAssemblerT3' ], recipe:{ time:10, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:2 },{ id:'item_factorioElectronicCircuit', count:20 },{ id:'item_factorioSulfuricAcid', count:5 }] } },
        { id:'item_factorioElectricEngineUnit', label:'item_factorioElectricEngineUnit', img:'img/factorio/ElectricEngineUnit.png', reqs:[{ id:'item_factorioElectricEngineUnitTech', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT2','item_factorioAssemblerT3' ], recipe:{ time:10, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:2 },{ id:'item_factorioEngineUnit', count:1 },{ id:'item_factorioLubricant', count:15 }] } },
        { id:'item_factorioRocketFuel', label:'item_factorioRocketFuel', img:'img/factorio/RocketFuel.png', reqs:[{ id:'item_factorioRocketFuelTech', count:1 }], storage:{ base:10, id:'item_factorioChest', count:10 }, machines:[ 'item_factorioAssemblerT2','item_factorioAssemblerT3' ], recipe:{ time:30, output:1, inputs:[{ id:'item_factorioLightOil', count:10 },{ id:'item_factorioSolidFuel', count:10 }] } },
        //---
        { id:'item_factorioChest', label:'item_factorioChest', img:'img/factorio/Chest.png', reqs:[{ id:'item_factorioSteelTech', count:1 }], machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:0.5, output:1, inputs:[{ id:'item_factorioSteelPlate', count:8 }] } },
        { id:'item_factorioBarrel', label:'item_factorioBarrel', img:'img/factorio/Barrel.png', reqs:[{ id:'item_factorioFluidHandling', count:1 }], machines:[ 'item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:1, output:1, inputs:[{ id:'item_factorioSteelPlate', count:1 }] } },
        { id:'item_factorioStorageTank', label:'item_factorioStorageTank', img:'img/factorio/StorageTank.png', reqs:[{ id:'item_factorioFluidHandling', count:1 }], machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:3, output:1, inputs:[{ id:'item_factorioIronPlate', count:20 },{ id:'item_factorioSteelPlate', count:5 }] } },
        { id:'item_factorioAccumulator', label:'item_factorioAccumulator', img:'img/factorio/Accumulator.png', reqs:[{ id:'item_factorioAccumulatorTech', count:1 }], machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:10, output:1, inputs:[{ id:'item_factorioBattery', count:5 },{ id:'item_factorioIronPlate', count:2 }] } },
        //---
        { id:'item_factorioSpeedModule1', label:'item_factorioSpeedModule1', img:'img/factorio/SpeedModule1.png', reqs:[{ id:'item_factorioSpeed1', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:15, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioElectronicCircuit', count:5 }] }, bonuses:{ energy:1.5, speed:1.2 } },
        { id:'item_factorioSpeedModule2', label:'item_factorioSpeedModule2', img:'img/factorio/SpeedModule2.png', reqs:[{ id:'item_factorioSpeed2', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:30, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioProcessingUnit', count:5 },{ id:'item_factorioSpeedModule1', count:4 }] }, bonuses:{ energy:1.6, speed:1.3 } },
        { id:'item_factorioSpeedModule3', label:'item_factorioSpeedModule3', img:'img/factorio/SpeedModule3.png', reqs:[{ id:'item_factorioSpeed3', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:60, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioProcessingUnit', count:5 },{ id:'item_factorioSpeedModule2', count:5 }] }, bonuses:{ energy:1.7, speed:1.5 } },
        //---
        { id:'item_factorioProductivityModule1', label:'item_factorioProductivityModule1', img:'img/factorio/ProductivityModule1.png', reqs:[{ id:'item_factorioProductivity1', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:15, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioElectronicCircuit', count:5 }] }, bonuses:{ output:1.04, energy:1.4, speed:0.95, pollution:1.05 } },
        { id:'item_factorioProductivityModule2', label:'item_factorioProductivityModule2', img:'img/factorio/ProductivityModule2.png', reqs:[{ id:'item_factorioProductivity2', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:30, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioProcessingUnit', count:5 },{ id:'item_factorioProductivityModule1', count:4 }] }, bonuses:{ output:1.06, energy:1.6, speed:0.9, pollution:1.07 } },
        { id:'item_factorioProductivityModule3', label:'item_factorioProductivityModule3', img:'img/factorio/ProductivityModule3.png', reqs:[{ id:'item_factorioProductivity3', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:60, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioProcessingUnit', count:5 },{ id:'item_factorioProductivityModule2', count:5 }] }, bonuses:{ output:1.1, energy:1.8, speed:0.85, pollution:1.1 } },
        //---
        { id:'item_factorioEfficiencyModule1', label:'item_factorioEfficiencyModule1', img:'img/factorio/EfficiencyModule1.png', reqs:[{ id:'item_factorioEfficiency1', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:15, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioElectronicCircuit', count:5 }] }, bonuses:{ energy:0.7 } },
        { id:'item_factorioEfficiencyModule2', label:'item_factorioEfficiencyModule2', img:'img/factorio/EfficiencyModule2.png', reqs:[{ id:'item_factorioEfficiency2', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:30, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioProcessingUnit', count:5 },{ id:'item_factorioEfficiencyModule1', count:4 }] }, bonuses:{ energy:0.6 } },
        { id:'item_factorioEfficiencyModule3', label:'item_factorioEfficiencyModule3', img:'img/factorio/EfficiencyModule3.png', reqs:[{ id:'item_factorioEfficiency3', count:1 }], storage:{ base:50, id:'item_factorioChest', count:50 }, machines:[ 'item_factorioAssemblerT1','item_factorioAssemblerT2','item_factorioAssemblerT3' ], manual:true, recipe:{ time:60, output:1, inputs:[{ id:'item_factorioAdvancedCircuit', count:5 },{ id:'item_factorioProcessingUnit', count:5 },{ id:'item_factorioEfficiencyModule2', count:5 }] }, bonuses:{ energy:0.5 } },
        //---
        { id:'item_factorioRocketSilo', label:'item_factorioRocketSilo', img:'img/factorio/RocketSilo.png', reqs:[{ id:'item_factorioRocketSiloTech', count:1 }], cases:81, speed:1, moduleSlots:4, energy:{ id:'item_factorioElectricity', count:4000 }, manual:true, recipe:{ time:30, output:1, inputs:[{ id:'item_factorioConcrete', count:1000 },{ id:'item_factorioElectricEngineUnit', count:200 },{ id:'item_factorioIronPlate', count:100 },{ id:'item_factorioProcessingUnit', count:200 },{ id:'item_factorioSteelPlate', count:1000 }] } },
        //---
        { id:'item_factorioRocketPart', label:'item_factorioRocketPart', img:'img/factorio/RocketPart.png', reqs:[{ id:'item_factorioRocketSiloTech', count:1 }], storage:{ base:5, id:'item_factorioChest', count:5 }, machines:[ 'item_factorioRocketSilo' ], recipe:{ time:3, output:1, inputs:[{ id:'item_factorioLowDensityStructure', count:10 },{ id:'item_factorioRocketControlUnit', count:10 },{ id:'item_factorioRocketFuel', count:10 }] } },
        //---
        { id:'item_factorioLab', label:'item_factorioLab', img:'img/factorio/Lab.png', cases:9, speed:1, moduleSlots:2, energy:{ id:'item_factorioElectricity', count:60 }, manual:true, recipe:{ time:3, output:1, inputs:[{ id:'item_factorioElectronicCircuit', count:10 },{ id:'item_factorioIronWheel', count:12 },{ id:'item_factorioIronPlate', count:2 }] } },
        //---
        { id:'item_factorioRedPack', label:'item_factorioRedPack', img:'img/factorio/RedPack.png', storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioLab' ], manual:true, recipe:{ time:5, output:1, inputs:[{ id:'item_factorioIronPlate', count:2 },{ id:'item_factorioCopperPlate', count:1 }] } },
        { id:'item_factorioGreenPack', label:'item_factorioGreenPack', img:'img/factorio/GreenPack.png', reqs:[{ id:'item_factorioGreenScience', count:1 }], storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioLab' ], manual:true, recipe:{ time:6, output:1, inputs:[{ id:'item_factorioIronPlate', count:6 },{ id:'item_factorioCopperPlate', count:2 }] } },
        { id:'item_factorioBluePack', label:'item_factorioBluePack', img:'img/factorio/BluePack.png', reqs:[{ id:'item_factorioBlueScience', count:1 }], storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioLab' ], manual:true, recipe:{ time:24, output:2, inputs:[{ id:'item_factorioSulfur', count:1 },{ id:'item_factorioAdvancedCircuit', count:3 },{ id:'item_factorioEngineUnit', count:2 }] } },
        { id:'item_factorioPurplePack', label:'item_factorioPurplePack', img:'img/factorio/PurplePack.png', reqs:[{ id:'item_factorioPurpleScience', count:1 }], storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioLab' ], manual:true, recipe:{ time:21, output:3, inputs:[{ id:'item_factorioIronPlate', count:15 },{ id:'item_factorioSteelPlate', count:30 },{ id:'item_factorioStone', count:30 },{ id:'item_factorioFurnaceT3', count:1 },{ id:'item_factorioProductivityModule1', count:1 }] } },
        { id:'item_factorioYellowPack', label:'item_factorioYellowPack', img:'img/factorio/YellowPack.png', reqs:[{ id:'item_factorioYellowScience', count:1 }], storage:{ base:200, id:'item_factorioChest', count:200 }, machines:[ 'item_factorioLab' ], manual:true, recipe:{ time:21, output:3, inputs:[{ id:'item_factorioProcessingUnit', count:2 },{ id:'item_factorioFlyingRobot', count:1 },{ id:'item_factorioLowDensityStructure', count:3 }] } },
    ],
    //---
    techs:[
        //---
        { id:'item_factorioAutomation1', label:'item_factorioAutomation1', img:'img/factorio/Automation1.png', storage:{ base:1 }, manual:true, recipe:{ time:100, output:1, inputs:[{ id:'item_factorioRedPack', count:10 }] } },
    ],
}
